server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/college?useSSL=false
    username: admin
    password: admin
    initialization-mode: always

  jooq:
    sql-dialect: MYSQL